(ns kagami.core-test
  (:require [clojure.test :refer [deftest is testing]]
            [kotoba.lang.text :as str]
            [kagami.db :as db]
            [kagami.did :as did]
            [kagami.grant :as grant]
            [kagami.p2p]
            [kagami.ci]
            [kagami.governor-bridge]
            [kagami.pin :as pin]
            [kagami.sync :as sync]
            [kagami.ws :as ws]
            [kagami.west :as west]))

(def fixture
  (str/join "\n"
   ["# west.yml — generated by scripts/gen-west-manifest.cljs. DO NOT EDIT BY HAND."
    "manifest:"
    "  version: \"1.0\""
    ""
    "  remotes:"
    "    - name: kotoba-lang"
    "      url-base: git@github.com:kotoba-lang"
    "    - name: gftdcojp"
    "      url-base: git@github.com:gftdcojp"
    ""
    "  defaults:"
    "    revision: main"
    ""
    "  group-filter: [+kotoba-lang, -datalad, -archived]"
    ""
    "  projects:"
    "    - name: plain"
    "      remote: kotoba-lang"
    "      revision: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "      path: orgs/kotoba-lang/plain"
    "      groups: [kotoba-lang]"
    "    - name: heavy-sub"
    "      remote: kotoba-lang"
    "      revision: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    "      path: orgs/kotoba-lang/heavy-sub"
    "      clone-depth: 1"
    "      groups: [kotoba-lang]"
    "      submodules: true"
    "    - name: selective-sub"
    "      remote: kotoba-lang"
    "      revision: ffffffffffffffffffffffffffffffffffffffff"
    "      path: orgs/kotoba-lang/selective-sub"
    "      clone-depth: 1"
    "      groups: [kotoba-lang]"
    "      submodules:"
    "        - path: 50-infra/a/lib/forge-std"
    "        - path: 50-infra/b/lib/forge-std"
    "    - name: annexed"
    "      remote: gftdcojp"
    "      revision: cccccccccccccccccccccccccccccccccccccccc"
    "      path: orgs/gftdcojp/annexed"
    "      groups: [datalad]"
    "      userdata:"
    "        datalad: true"
    "        annex-remote: b2"
    "    - name: retired"
    "      remote: gftdcojp"
    "      revision: dddddddddddddddddddddddddddddddddddddddd"
    "      path: orgs/gftdcojp/retired"
    "      groups: [archived]"
    "      userdata:"
    "        archived: true"
    "    - name: gftdcojp-aliased"
    "      remote: gftdcojp"
    "      repo-path: aliased"
    "      revision: eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
    "      path: orgs/gftdcojp/aliased"
    "      groups: [gftdcojp]"
    ""
    "  self:"
    "    path: manifest"
    "    west-commands: west-commands.yml"
    ""]))

(deftest parse-emit-bijection
  (is (= fixture (west/emit (west/parse fixture)))))

;; Radicle 実登録の RID を west.yml userdata で運ぶ(superproject
;; manifest/repos.edn :manifest.repos/rad-rids の projection)。未知の
;; userdata フィールドは parse が例外を投げる仕様なので、生成器側の
;; `rad-rid:` 出力とここが揃っていないと reconcile が丸ごと落ちる。
(def rad-fixture
  (str/join "\n"
   ["# west.yml — generated by scripts/gen-west-manifest.cljs. DO NOT EDIT BY HAND."
    "manifest:"
    "  version: \"1.0\""
    ""
    "  remotes:"
    "    - name: kotoba-lang"
    "      url-base: git@github.com:kotoba-lang"
    ""
    "  defaults:"
    "    revision: main"
    ""
    "  group-filter: [+kotoba-lang]"
    ""
    "  projects:"
    "    - name: radicled"
    "      remote: kotoba-lang"
    "      revision: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "      path: orgs/kotoba-lang/radicled"
    "      groups: [kotoba-lang]"
    "      userdata:"
    "        rad-rid: rad:z8g6evEq3KDp3GU5tT8KyzyekE6D"
    "    - name: annexed-and-radicled"
    "      remote: kotoba-lang"
    "      revision: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    "      path: orgs/kotoba-lang/annexed-and-radicled"
    "      groups: [datalad]"
    "      userdata:"
    "        datalad: true"
    "        annex-remote: b2"
    "        rad-rid: rad:z35iT2FBX6eRTmvyaM4vwbYko4oc"
    ""
    "  self:"
    "    path: manifest"
    "    west-commands: west-commands.yml"
    ""]))

(deftest rad-rid-userdata
  (testing "parse/emit bijection over the rad-rid dialect"
    (is (= rad-fixture (west/emit (west/parse rad-fixture)))))
  (let [d (west/parse rad-fixture)]
    (testing "rad-rid alone"
      (is (= {:rad-rid "rad:z8g6evEq3KDp3GU5tT8KyzyekE6D"}
             (:repo/userdata (west/find-repo d "radicled")))))
    (testing "rad-rid coexists with datalad (both must survive one userdata block)"
      (is (= {:datalad true :annex-remote "b2"
              :rad-rid "rad:z35iT2FBX6eRTmvyaM4vwbYko4oc"}
             (:repo/userdata (west/find-repo d "annexed-and-radicled")))))))

(deftest parse-shapes
  (let [d (west/parse fixture)]
    (testing "entity fields"
      (is (= 6 (count (:fleet/repos d))))
      (is (= {:repo/name "heavy-sub" :repo/remote "kotoba-lang"
              :repo/revision "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
              :repo/path "orgs/kotoba-lang/heavy-sub" :repo/clone-depth 1
              :repo/groups ["kotoba-lang"] :repo/submodules? true}
             (west/find-repo d "heavy-sub")))
      (is (= {:repo/name "selective-sub" :repo/remote "kotoba-lang"
              :repo/revision "ffffffffffffffffffffffffffffffffffffffff"
              :repo/path "orgs/kotoba-lang/selective-sub" :repo/clone-depth 1
              :repo/groups ["kotoba-lang"] :repo/submodules? true
              :repo/submodule-paths ["50-infra/a/lib/forge-std"
                                     "50-infra/b/lib/forge-std"]}
             (west/find-repo d "selective-sub")))
      (is (= {:datalad true :annex-remote "b2"}
             (:repo/userdata (west/find-repo d "annexed"))))
      (is (= {:archived true} (:repo/userdata (west/find-repo d "retired"))))
      (is (= "aliased" (:repo/repo-path (west/find-repo d "gftdcojp-aliased")))))
    (testing "remotes + url"
      (is (= "git@github.com:kotoba-lang/plain"
             (west/remote-url d (west/find-repo d "plain"))))
      (is (= "git@github.com:gftdcojp/aliased"
             (west/remote-url d (west/find-repo d "gftdcojp-aliased")))))
    (testing "queries"
      (is (= {:repos 6 :orgs 2 :heavy 2 :datalad 1 :archived 1} (db/stats d)))
      (is (= ["annexed" "retired" "gftdcojp-aliased"]
             (mapv :repo/name (db/by-org d "gftdcojp")))))))

(deftest pin-advance
  (let [d  (west/parse fixture)
        ev (db/pin-advance-event
            [] {:repo "plain"
                :old-rev "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                :new-rev "1111111111111111111111111111111111111111"
                :actor "test" :at "2026-07-16T00:00:00Z"})
        d' (db/apply-pin-advance d ev)]
    (is (= 1 (:event/seq ev)))
    (is (= "1111111111111111111111111111111111111111"
           (:repo/revision (west/find-repo d' "plain"))))
    (testing "projection reflects the advance and nothing else"
      (is (= (str/replace fixture "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                          "1111111111111111111111111111111111111111")
             (west/emit d'))))
    (is (thrown? #?(:clj Exception :cljs js/Error)
                 (db/apply-pin-advance d (assoc ev :repo/name "nope"))))))

(deftest sync-planner
  (let [d (west/parse fixture)
        e (west/find-repo d "plain")]
    (testing "missing dir -> materialize, pinned SHA fetched directly"
      (let [{:keys [action steps]} (sync/plan d e {:exists? false} "/ws/orgs/kotoba-lang/plain")]
        (is (= :materialize action))
        (is (= ["git" "-C" "/ws/orgs/kotoba-lang/plain" "fetch" "origin"
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
               (nth steps 2))
            "FULL history — shallow stopped being the default on 2026-07-21
             (ADR-2607211600), and a planner that kept it would put the grafts
             back one repo at a time")))
    (testing "a repo that ASKS for a depth still gets it"
      (let [heavy (west/find-repo d "heavy-sub")
            {:keys [steps]} (sync/plan d heavy {:exists? true :dirty? false :head "old"} "/ws/h")]
        (is (= ["git" "-C" "/ws/h" "fetch" "--depth" "1" "origin"
                "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"]
               (first steps))
            "clone-depth is an entity's own declaration, not a default")))
    (testing "dirty checkout is skipped, never overwritten (west semantics)"
      (is (= :skip-dirty (:action (sync/plan d e {:exists? true :dirty? true :head "x"} "/ws/p")))))
    (testing "clean at pin -> noop"
      (is (= :noop (:action (sync/plan d e {:exists? true :dirty? false
                                            :head (:repo/revision e)} "/ws/p")))))
    (testing "clean behind pin -> advance"
      (is (= :advance (:action (sync/plan d e {:exists? true :dirty? false :head "old"} "/ws/p")))))
    (testing "working-set selectors"
      (is (= ["plain" "heavy-sub" "selective-sub"]
             (mapv :repo/name (sync/working-set d {:org "kotoba-lang"}))))
      (is (= ["annexed"] (mapv :repo/name (sync/working-set d {:group "datalad"}))))
      (is (= ["retired"] (mapv :repo/name (sync/working-set d {:names ["retired"]})))))))

;; ---------------------------------------------------------------------------
;; Phase 1: signed pin admission gate (pure — fake crypto ports)

(def ^:private fake-hash #(str "H" (count %)))
;; fake signature scheme: sig is valid iff it equals "SIG:" + pubkey + payload hash
(defn- fake-sign [pubkey payload] (str "SIG:" pubkey ":" (fake-hash payload)))
(defn- fake-verify [pubkey payload sig] (= sig (fake-sign pubkey payload)))

(def ^:private keyring
  {:keys {"ed25519:agentA" {:grants #{"orgs/kotoba-lang/*"}}
          "ed25519:agentB" {:grants #{"orgs/gftdcojp/one-repo"}}}})

(defn- proposal [pubkey rec]
  {:record rec :signature (fake-sign pubkey (pin/canonical-str rec)) :signer (str "ed25519:" pubkey)})

(defn- ctx [current & {:as extra}]
  (merge {:repo-path "orgs/kotoba-lang/plain" :current current :keyring keyring
          :verify-fn fake-verify :hash-fn fake-hash :reachable? true}
         extra))

(deftest pin-admission-gate
  (let [genesis (pin/make-record {:repo "plain" :value "aaa" :sequence 1 :parent nil})
        g-prop  (proposal "agentA" genesis)
        g-cur   {:record genesis :signature (:signature g-prop)}
        next-ok (pin/make-record {:repo "plain" :value "bbb" :sequence 2
                                  :parent (pin/record-hash fake-hash genesis (:signature g-prop))})]
    (testing "genesis accept"
      (is (= :accept (:verdict (pin/admit g-prop (ctx nil))))))
    (testing "valid advance accepts"
      (is (= :accept (:verdict (pin/admit (proposal "agentA" next-ok) (ctx g-cur))))))
    (testing "sequence rollback rejected even with a valid signature"
      (let [bad (assoc next-ok :pin/sequence 1)]
        (is (some #{:sequence-rollback}
                  (:reasons (pin/admit (proposal "agentA" bad) (ctx g-cur)))))))
    (testing "parent mismatch (replay) rejected"
      (let [bad (assoc next-ok :pin/parent "H999")]
        (is (some #{:parent-mismatch}
                  (:reasons (pin/admit (proposal "agentA" bad) (ctx g-cur)))))))
    (testing "unauthorized signer rejected (grant does not cover the path)"
      (is (some #{:unauthorized-signer}
                (:reasons (pin/admit (proposal "agentB" next-ok) (ctx g-cur))))))
    (testing "tampered record fails signature"
      (let [p (proposal "agentA" next-ok)
            tampered (assoc-in p [:record :pin/value] "evil")]
        (is (some #{:bad-signature}
                  (:reasons (pin/admit tampered (ctx g-cur)))))))
    (testing "unreachable pin rejected; unverifiable warn-accepts (fail-open)"
      (is (some #{:unreachable-from-upstream-default-branch}
                (:reasons (pin/admit (proposal "agentA" next-ok) (ctx g-cur :reachable? false)))))
      (is (= :warn-accept
             (:verdict (pin/admit (proposal "agentA" next-ok) (ctx g-cur :reachable? :unknown))))))
    (testing "grant wildcard semantics"
      (is (pin/authorized? keyring "ed25519:agentA" "orgs/kotoba-lang/anything"))
      (is (not (pin/authorized? keyring "ed25519:agentA" "orgs/gftdcojp/x")))
      (is (pin/authorized? keyring "ed25519:agentB" "orgs/gftdcojp/one-repo")))))

(deftest pin-value-regression
  (let [genesis (pin/make-record {:repo "plain" :value "new" :sequence 1 :parent nil})
        g-prop  (proposal "agentA" genesis)
        g-cur   {:record genesis :signature (:signature g-prop)}
        back    (pin/make-record {:repo "plain" :value "old" :sequence 2
                                  :parent (pin/record-hash fake-hash genesis (:signature g-prop))})]
    (testing "value regression rejected even with valid signature + advancing sequence"
      (is (= {:verdict :reject :reasons [:value-regression]}
             (pin/admit (proposal "agentA" back) (ctx g-cur :value-advance? false)))))
    (testing "unverifiable value-advance warn-accepts (fail-open, like Rule 2 repair path)"
      (is (= :warn-accept
             (:verdict (pin/admit (proposal "agentA" back) (ctx g-cur :value-advance? :unknown))))))
    (testing "genesis ignores value-advance"
      (is (= :accept (:verdict (pin/admit g-prop (ctx nil :value-advance? true))))))))

;; ---------------------------------------------------------------------------
;; Phase 2: did:key, delegation chains, quorum canonical advance

(deftest did-key-roundtrip
  (let [hex "7414dd47730947339b50c97b85021f22beee825dacc9e5c30b8413973215c5dd"
        d (did/pubkey-hex->did hex)]
    (is (str/starts-with? d "did:key:z6Mk"))
    (is (= hex (did/did->pubkey-hex d)))
    (is (thrown? #?(:clj Exception :cljs js/Error) (did/did->pubkey-hex "did:web:x")))))

;; fake link signatures: reuse fake-sign over link payload keyed by iss pubkey.
;; dids must decode, so build them from real-shaped hex pubkeys.
(def ^:private hexA (apply str (repeat 32 "aa")))
(def ^:private hexB (apply str (repeat 32 "bb")))
(def ^:private hexC (apply str (repeat 32 "cc")))
(def ^:private didA (did/pubkey-hex->did hexA))
(def ^:private didB (did/pubkey-hex->did hexB))
(def ^:private didC (did/pubkey-hex->did hexC))

(defn- mk-link [iss aud resources exp]
  (let [l {:grant/iss iss :grant/aud aud :grant/resources resources :grant/exp exp}]
    (assoc l :grant/sig (fake-sign (did/did->pubkey-hex iss) (grant/link-canonical l)))))

(deftest delegation-chain
  (let [gctx {:roots #{didA} :verify-fn fake-verify :now "2026-07-16T00:00:00Z"}
        root->b (mk-link didA didB #{"pin:orgs/kotoba-lang/*" "land:orgs/kotoba-lang/*"} "2026-08-01T00:00:00Z")
        b->c    (mk-link didB didC #{"land:orgs/kotoba-lang/kotoba-fleet-vcs"} "2026-07-20T00:00:00Z")]
    (testing "valid 2-link chain, attenuated"
      (let [v (grant/verify-chain [root->b b->c] gctx)]
        (is (:ok? v))
        (is (= didC (:holder v)))
        (is (grant/holds? v "land:orgs/kotoba-lang/kotoba-fleet-vcs"))
        (is (not (grant/holds? v "land:orgs/kotoba-lang/other")))))
    (testing "escalation rejected"
      (let [esc (mk-link didB didC #{"land:orgs/gftdcojp/*"} "2026-07-20T00:00:00Z")]
        (is (some #{:attenuation-violation}
                  (:reasons (grant/verify-chain [root->b esc] gctx))))))
    (testing "untrusted root / broken linkage / expiry / tamper"
      (is (some #{:root-not-trusted}
                (:reasons (grant/verify-chain [(mk-link didB didC #{"x"} nil)] gctx))))
      (is (some #{:broken-linkage}
                (:reasons (grant/verify-chain
                           [root->b (mk-link didC didB #{"land:orgs/kotoba-lang/x"} nil)] gctx))))
      (is (some #{:expired}
                (:reasons (grant/verify-chain
                           [(mk-link didA didB #{"x"} "2026-07-01T00:00:00Z")] gctx))))
      (is (some #{:bad-link-signature}
                (:reasons (grant/verify-chain
                           [(assoc root->b :grant/resources #{"pin:orgs/*"})] gctx)))))))

(deftest quorum-canonical-advance
  (let [policy {:allow #{didA didB didC} :threshold 2}
        rec    (pin/make-record {:repo "plain" :value "v2" :sequence 1 :parent nil})
        sig-by (fn [hexk] {:signer (did/pubkey-hex->did hexk)
                           :signature (fake-sign hexk (pin/canonical-str rec))})
        qctx   {:policy policy :current nil :verify-fn fake-verify
                :hash-fn fake-hash :reachable? true}]
    (testing "2-of-3 accepts"
      (is (= :accept (:verdict (grant/admit-quorum
                                {:record rec :signatures [(sig-by hexA) (sig-by hexB)]} qctx)))))
    (testing "1-of-3 rejected"
      (is (= [:quorum-not-met]
             (:reasons (grant/admit-quorum {:record rec :signatures [(sig-by hexA)]} qctx)))))
    (testing "duplicate signer counts once"
      (is (some #{:quorum-not-met}
                (:reasons (grant/admit-quorum
                           {:record rec :signatures [(sig-by hexA) (sig-by hexA)]} qctx)))))
    (testing "outsider signature does not count"
      (let [hexZ (apply str (repeat 32 "dd"))]
        (is (some #{:quorum-not-met}
                  (:reasons (grant/admit-quorum
                             {:record rec :signatures [(sig-by hexA)
                                                       {:signer (did/pubkey-hex->did hexZ)
                                                        :signature (fake-sign hexZ (pin/canonical-str rec))}]}
                             qctx))))))))

(deftest reconcile-drift
  (let [d0 (west/parse fixture)
        d1 (-> d0
               (db/apply-pin-advance {:repo/name "plain" :pin/new "f111111111111111111111111111111111111111"})
               (update :fleet/repos conj {:repo/name "newbie" :repo/remote "kotoba-lang"
                                          :repo/revision "f222222222222222222222222222222222222222"
                                          :repo/path "orgs/kotoba-lang/newbie" :repo/groups ["kotoba-lang"]})
               (update :fleet/repos (fn [rs] (vec (remove #(= "retired" (:repo/name %)) rs)))))
        diff (db/diff-dbs d0 d1)]
    (is (db/drift? diff))
    (is (= [{:name "plain" :old "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
             :new "f111111111111111111111111111111111111111"}] (:changed diff)))
    (is (= ["newbie"] (mapv :repo/name (:added diff))))
    (is (= ["retired"] (:removed diff)))
    (is (not (:meta-changed? diff)))
    (let [evs (db/reconcile-events [{:event/seq 5}] diff "2026-07-16T00:00:00Z")]
      (is (= [6 7 8] (mapv :event/seq evs)))
      (is (= [:pin/reconcile-legacy :repo/added-legacy :repo/removed-legacy]
             (mapv :event/type evs))))
    (is (not (db/drift? (db/diff-dbs d0 d0))))))

(deftest ws-gc-policy
  (let [wss [{:path "a" :age-h 1 :dirty? false}
             {:path "b" :age-h 10 :dirty? false}
             {:path "c" :age-h 30 :dirty? true}
             {:path "d" :age-h 50 :dirty? false}
             {:path "e" :age-h 5 :dirty? false}]]
    (testing "expired removed, dirty never, count cap enforced oldest-first"
      (let [{:keys [remove keep skipped-dirty]} (ws/gc-plan wss {:max-age-h 24 :max-count 2})]
        (is (= ["d" "b"] remove))          ;; d expired; b over count-cap (oldest alive)
        (is (= ["a" "e"] keep))
        (is (= ["c"] skipped-dirty))))
    (testing "no caps -> keep all clean"
      (is (empty? (:remove (ws/gc-plan wss {})))))))

;; ---------------------------------------------------------------------------
;; Phase 3b: fleet head gossip replication (wire-compatible with p2p)

(defn- signed-head [pubkey seq value]
  (let [rec (pin/make-record {:repo "fleet-db" :value value :sequence seq :parent nil})]
    {:record rec
     :signature (fake-sign pubkey (pin/canonical-str rec))
     :signer (str "did:key:" pubkey)}))

(deftest p2p-fleet-head-replication
  (let [trust #{"did:key:pkOwner"}
        ctx {:trust trust :verify-fn fake-verify
             :did->pubkey #(subs % (count "did:key:"))}
        head5 (signed-head "pkOwner" 5 "content-hash-5")
        ann5  (kagami.p2p/head->announce head5 "machineA")]
    (testing "announce shape is p2p-wire-compatible"
      (is (= :head-announce (:type ann5)))
      (is (= "fleet-db" (:graph ann5)))
      (is (= 5 (:seq ann5)))
      (is (= "content-hash-5" (:head-cid ann5))))
    (testing "trusted signed announce verifies"
      (is (:ok? (kagami.p2p/verify-announce ann5 ctx))))
    (testing "machine B with no head adopts A's head"
      (let [b (kagami.p2p/adopt (kagami.p2p/new-node "machineB") ann5 ctx)]
        (is (= 5 (:seq (kagami.p2p/local-head b))))
        (is (= "content-hash-5" (:head-cid (kagami.p2p/local-head b))))))
    (testing "stale announce (lower seq) is ignored"
      (let [b (-> (kagami.p2p/new-node "machineB")
                  (kagami.p2p/adopt ann5 ctx)
                  (kagami.p2p/adopt (kagami.p2p/head->announce
                                    (signed-head "pkOwner" 3 "old") "machineA") ctx))]
        (is (= 5 (:seq (kagami.p2p/local-head b))))))
    (testing "untrusted signer rejected + not adopted"
      (let [ann (kagami.p2p/head->announce (signed-head "pkEvil" 9 "evil") "machineX")]
        (is (some #{:untrusted-signer} (:reasons (kagami.p2p/verify-announce ann ctx))))
        (is (= 5 (:seq (kagami.p2p/local-head
                        (kagami.p2p/adopt (kagami.p2p/adopt (kagami.p2p/new-node "b") ann5 ctx)
                                         ann ctx)))))))
    (testing "tampered head-cid rejected"
      (let [ann (assoc ann5 :head-cid "swapped")]
        (is (some #{:head-cid-mismatch} (:reasons (kagami.p2p/verify-announce ann ctx))))))
    (testing "forged signature rejected"
      (let [bad (assoc-in ann5 [:fleet-head :signature] "deadbeef")]
        (is (some #{:bad-signature} (:reasons (kagami.p2p/verify-announce bad ctx))))))))

(deftest agent-registry-merge
  ;; merge-registry lives in the CLI; test the pure semantics inline here
  ;; via the same logic to lock the contract.
  (let [keyring {:keys {"ed25519:gov" {:grants #{"orgs/*"}}}
                 :delta/editors #{"did:key:gov"}}
        entry {:signer "ed25519:agentX" :did "did:key:agentX"
               :grants #{"orgs/kotoba-lang/*"} :agent "sessionX"}
        merged (-> keyring
                   (update-in [:keys "ed25519:agentX"] #(or % {:grants (:grants entry)}))
                   (update :delta/editors conj (:did entry)))]
    (testing "enrolled agent key added with its scoped grant"
      (is (= #{"orgs/kotoba-lang/*"} (get-in merged [:keys "ed25519:agentX" :grants]))))
    (testing "governance key preserved, editor set grows"
      (is (= #{"orgs/*"} (get-in merged [:keys "ed25519:gov" :grants])))
      (is (contains? (:delta/editors merged) "did:key:agentX")))
    (testing "governance wins: enrolled key cannot override an existing grant"
      (let [collide (update-in keyring [:keys "ed25519:gov"] #(or % {:grants #{"orgs/evil/*"}}))]
        (is (= #{"orgs/*"} (get-in collide [:keys "ed25519:gov" :grants])))))))

(deftest scope-diff-staged-flip
  (let [d0 (west/parse fixture)
        ;; drift: change a kotoba-lang pin AND a gftdcojp pin
        d1 (-> d0
               (db/apply-pin-advance {:repo/name "plain" :pin/new "f111111111111111111111111111111111111111"})
               (db/apply-pin-advance {:repo/name "annexed" :pin/new "f222222222222222222222222222222222222222"}))
        full (db/diff-dbs d0 d1)
        kl-only (db/scope-diff full d1 #{"kotoba-lang"})]
    (testing "full diff sees both orgs' drift"
      (is (= 2 (count (:changed full)))))
    (testing "scoped to kotoba-lang: only the kotoba-lang pin is in-scope"
      (is (= ["plain"] (map :name (:changed kl-only))))
      (is (db/drift? kl-only)))
    (testing "scoped to gftdcojp: only the gftdcojp pin"
      (is (= ["annexed"] (map :name (:changed (db/scope-diff full d1 #{"gftdcojp"}))))))
    (testing "scoped to an untouched org: no in-scope drift (would not reject)"
      (is (not (db/drift? (db/scope-diff full d1 #{"etzhayyim"})))))))

(deftest ci-receipt
  (let [h #(str "H" (hash %))
        sign (fn [payload] (str "S:" payload))
        vfy (fn [pub payload sig] (= sig (str "S:" payload)))
        checks [{:name :pin-reachable/a :outcome :pass}
                {:name :pin-reachable/b :outcome :pass}]
        req #{:pin-reachable/a :pin-reachable/b}
        r (kagami.ci/make-receipt {:subject {:repos ["a" "b"]} :checks checks
                                  :required req :policy "p" :at "t"})
        signed (kagami.ci/sign-receipt h sign "did:key:zA" r)]
    (testing "verdict pass iff required subset passed"
      (is (= :pass (:ci/outcome r)))
      (is (= :fail (:ci/outcome (kagami.ci/make-receipt
                                 {:subject {} :checks [{:name :x :outcome :fail}]
                                  :required #{:x} :at "t"})))))
    (testing "signed receipt verifies; tamper + inconsistent-outcome rejected"
      (is (:ok? (kagami.ci/verify-receipt h vfy signed "pkA")))
      (is (some #{:cid-mismatch}
                (:reasons (kagami.ci/verify-receipt h vfy (assoc signed :cid "H0") "pkA"))))
      (let [lie (assoc-in signed [:receipt :ci/outcome] :pass)
            lie (assoc-in lie [:receipt :ci/checks] [{:name :pin-reachable/a :outcome :fail}])]
        (is (not (:ok? (kagami.ci/verify-receipt h vfy lie "pkA"))))))
    (testing "gate detail carries the runner's own output tail as evidence"
      ;; "exit 0" alone cannot distinguish a real pass from ADR-2607178000's
      ;; false pass (clojure dropping to a REPL in an empty dir also exits 0).
      ;; 直近 3 行だけ残す（先頭の java -version 行は落ちる）。
      (is (= "exit 0 — Testing kagitaba.core-test | Ran 18 tests containing 107 assertions. | 0 failures, 0 errors."
             (kagami.ci/gate-detail 0 (str "openjdk version 26\n\nTesting kagitaba.core-test\n"
                                          "Ran 18 tests containing 107 assertions.\n0 failures, 0 errors.\n"))))
      (is (= "exit 0 — (no output)" (kagami.ci/gate-detail 0 "   \n\n")))
      (is (str/starts-with? (kagami.ci/gate-detail 1 "boom") "exit 1 — boom"))
      (let [d (kagami.ci/gate-detail 0 (apply str (repeat 400 "x")))]
        (is (<= (count d) (+ 20 kagami.ci/gate-detail-max)))
        (is (str/includes? d "…")))
      ;; A failing gate's own output is the only artifact anyone acts on, and a
      ;; three-line tail never carried it: the runner harness prints its
      ;; epilogue AFTER the diagnosis. This is the real output amu-native-fuzz
      ;; produced on fleet node simeon on 2026-08-19, abbreviated only in the
      ;; middle. Under the old budget the receipt read `FLEET-CI: native fuzz
      ;; exited 1 | FLEET-CI-EXIT: 1 | FLEET-CI: gate did not report success`
      ;; -- three lines saying THAT it failed and none saying why, which cost a
      ;; manual ssh to that node to find out.
      (let [real-failure
            (str "native-fuzz: building\n"
                 "/tmp/amu/tools/kexe_loader.c:495:31: runtime error: applying zero offset to null pointer\n"
                 "    #0 0x000104e167b8 in resolve_string_bytes kexe_loader.c\n"
                 "    #1 0x000104e0d468 in checked_string_substring kexe_loader.c:1157\n"
                 "    #2 0x000104e15304 in fuzz_handle_graph kexe_parser_fuzz.c:445\n"
                 "SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior kexe_loader.c:495:31\n"
                 "    at file:///opt/homebrew/lib/node_modules/nbb/lib/nbb_main.js:13:216\n"
                 "FLEET-CI: native fuzz exited 1\n"
                 "FLEET-CI-EXIT: 1\n"
                 "FLEET-CI: gate did not report success on simeon\n")
            d (kagami.ci/gate-detail 1 real-failure)]
        (is (str/includes? d "kexe_loader.c:495:31")
            "the receipt names the file and line the sanitizer named")
        (is (str/includes? d "resolve_string_bytes")
            "and the frame the fault is in")
        (is (str/includes? d "UndefinedBehaviorSanitizer")
            "and what kind of fault it was")
        (is (str/includes? d "FLEET-CI-EXIT: 1")
            "without dropping the epilogue that was all it used to carry")
        (is (<= (count d) (+ 20 kagami.ci/gate-detail-max-failed))
            "and a receipt is still a receipt"))
      ;; The wider budget is for failures only. A passing check stays terse --
      ;; its detail is confirmatory, and receipts should not grow for the
      ;; overwhelmingly common case.
      (let [chatty (str/join "\n" (map #(str "line " %) (range 40)))]
        (is (= 3 (count (str/split (kagami.ci/gate-detail 0 chatty) #" \| ")))
            "a passing gate still keeps three lines")
        (is (= 12 (count (str/split (kagami.ci/gate-detail 1 chatty) #" \| ")))
            "a failing one keeps twelve")))
    (testing "subject extras (tip-driven runner) are covered by the signature"
      ;; A tip-driven runner records WHICH commit it actually tested in the
      ;; subject (--subject-extra). That claim is worthless unless the
      ;; signature covers it: swapping the tested sha must invalidate the CID.
      (let [tipped (kagami.ci/make-receipt
                    {:subject {:repos ["a"] :tips {"a" "sha-1"} :trigger :tip-change}
                     :checks checks :required req :policy "fleet-ci/tip-verify/v1" :at "t"})
            other  (kagami.ci/make-receipt
                    {:subject {:repos ["a"] :tips {"a" "sha-2"} :trigger :tip-change}
                     :checks checks :required req :policy "fleet-ci/tip-verify/v1" :at "t"})
            s (kagami.ci/sign-receipt h sign "did:key:zA" tipped)]
        (is (= {"a" "sha-1"} (get-in tipped [:ci/subject :tips])))
        (is (not= (kagami.ci/receipt-cid h tipped) (kagami.ci/receipt-cid h other)))
        (is (:ok? (kagami.ci/verify-receipt h vfy s "pkA")))
        (is (some #{:cid-mismatch}
                  (:reasons (kagami.ci/verify-receipt
                             h vfy (assoc s :receipt other) "pkA"))))))))

(deftest scope-diff-repos-tightest-flip
  (let [d0 (west/parse fixture)
        d1 (-> d0
               (db/apply-pin-advance {:repo/name "plain" :pin/new "f111111111111111111111111111111111111111"})
               (db/apply-pin-advance {:repo/name "annexed" :pin/new "f222222222222222222222222222222222222222"}))
        full (db/diff-dbs d0 d1)]
    (testing "enforce-repos scopes rejection to named repos only"
      (is (= ["plain"] (map :name (:changed (db/scope-diff-repos full ["plain"])))))
      (is (db/drift? (db/scope-diff-repos full ["plain"]))))
    (testing "untouched repo scope -> no in-scope drift"
      (is (not (db/drift? (db/scope-diff-repos full ["heavy-sub"])))))
    (testing "both repos in scope"
      (is (= 2 (count (:changed (db/scope-diff-repos full ["plain" "annexed"]))))))))

(deftest cacao-payload-bridge
  (let [link {:grant/iss "did:key:zA" :grant/aud "did:key:zB"
              :grant/resources #{"pin:orgs/kotoba-lang/*" "land:orgs/kotoba-lang/kagami"}
              :grant/exp "2026-08-01T00:00:00Z"}
        payload (grant/grant->cacao-payload link)]
    (testing "fleet grant maps to a CAIP-122 CACAO payload (iss/aud/resources/exp)"
      (is (= "did:key:zA" (:iss payload)))
      (is (= "did:key:zB" (:aud payload)))
      (is (= ["land:orgs/kotoba-lang/kagami" "pin:orgs/kotoba-lang/*"] (:resources payload)))
      (is (= "2026-08-01T00:00:00Z" (:exp payload))))
    (testing "exp omitted when absent"
      (is (not (contains? (grant/grant->cacao-payload (dissoc link :grant/exp)) :exp))))))

(deftest governor-bridge-receipt-shape
  (let [outcome {:repo "kagami" :new-sha "80914e06f4c1c2ef56f1b5a91e9f7e628c519e56"
                 :seq 7 :verdict :accept :quorum 2 :threshold 2}
        r (kagami.governor-bridge/land->ops-receipt outcome 1)]
    (testing "fleet land-back maps to the ops-runner receipt shape"
      (is (= "kagami:80914e06f4c1" (:merged-cid r)))
      (is (= :fleet (:lane r)))
      (is (= "land|kagami|seq7" (:effect-id r)))
      (is (= :fleet/land-back (:kind r)))
      (is (= :accepted (:status r)))
      (is (= 1 (:ts r))))
    (testing "reject verdict -> :rejected status"
      (is (= :rejected (:status (kagami.governor-bridge/land->ops-receipt
                                 (assoc outcome :verdict :reject) 1)))))
    (testing "the signature-covered identity keys are all present"
      (is (every? r [:merged-cid :lane :effect-id :kind :status :ts])))))
